config/routes.rb
Rails.application.routes.draw do

  resources :admins
  root to: "security#evevator"

  

     resources :security do
       collection do
         get 'evevator'
         get 'entrance_guard'
         get 'park'
         get 'door'
         get 'infrared'
         get 'lighting'
         get 'air_condition'
         get 'dewatering'
         get 'phone'
         get 'chart'
       end
     end

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                   :integer          not null, primary key
#  picture              :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Admin < ActiveRecord::Base
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:picture)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/security_controller.rb
class SecurityController < ApplicationController
  def phone
  end

  def evevator
  end

  def entrance_guard
  end

  def park
  end

  def door
  end

  def infrared
  end

  def lighting
  end

  def air_condition
  end

  def dewatering
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
	def index
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_name(name)
		case name
		when "notice"
			"success"
		when "alert"
			"danger"
		else
			"info"
		end
	end

	# 左侧菜单栏对应图标
	def menu_tree_icon(menu)
		icons = { 
			'动力' => 'fa-paper-plane', '环境' => 'fa-globe', '联动' => 'fa-sitemap', '安全' => 'fa-check', '远程' => 'fa-cloud', 
			'能效' => 'fa-bar-chart', '部署' => 'fa-desktop', '报表' => 'fa-files-o', '告警记录' => 'fa-list-ul'
		}
		icons[menu] || 'fa-home'
	end
end

app/helpers/security_helper.rb
module SecurityHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin, url: admins_path, html: { multipart: true } do |form| %>
  <%= form.file_field :picture %>
<% end %>


<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title  back-change">
        <h5>Image cropper <small>http://fengyuanchen.github.io/cropper/</small></h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="#">Config option 1</a>
            </li>
            <li><a href="#">Config option 2</a>
            </li>
          </ul>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">
        <p>
          A simple jQuery image cropping plugin.
        </p>
        <div class="row">
          <div class="col-md-6">
            <div class="image-crop">
              <img src="img/p3.jpg">
            </div>
          </div>
          <div class="col-md-6">
            <h4>Preview image</h4>
            <div class="img-preview img-preview-sm"></div>
            <h4>Comon method</h4>
            <p>
                You can upload new image to crop container and easy download new cropped image.
            </p>
            <div class="btn-group">
              <label title="Upload image file" for="inputImage" class="btn btn-primary">
                <input type="file" accept="image/*" name="file" id="inputImage" class="hide">
                Upload new image
              </label>
              <label title="Donload image" id="download" class="btn btn-primary">Download</label>
            </div>
            <h4>Other method</h4>
            <p>
              You may set cropper options with <code>$({image}).cropper(options)</code>
            </p>
            <div class="btn-group">
              <button class="btn btn-white" id="zoomIn" type="button">Zoom In</button>
              <button class="btn btn-white" id="zoomOut" type="button">Zoom Out</button>
              <button class="btn btn-white" id="rotateLeft" type="button">Rotate Left</button>
              <button class="btn btn-white" id="rotateRight" type="button">Rotate Right</button>
              <button class="btn btn-warning" id="setDrag" type="button">New crop</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<script>
  $(document).ready(function(){

    var $image = $(".image-crop > img")
    $($image).cropper({
        aspectRatio: 1.618,
        preview: ".img-preview",
        done: function(data) {
            // Output the result data for cropping image.
        }
    });

    var $inputImage = $("#inputImage");
    if (window.FileReader) {
        $inputImage.change(function() {
            var fileReader = new FileReader(),
                    files = this.files,
                    file;

            if (!files.length) {
                return;
            }

            file = files[0];

            if (/^image\/\w+$/.test(file.type)) {
                fileReader.readAsDataURL(file);
                fileReader.onload = function () {
                    $inputImage.val("");
                    $image.cropper("reset", true).cropper("replace", this.result);
                };
            } else {
                showMessage("Please choose an image file.");
            }
        });
    } else {
        $inputImage.addClass("hide");
    }

    $("#download").click(function() {
        window.open($image.cropper("getDataURL"));
    });

    $("#zoomIn").click(function() {
        $image.cropper("zoom", 0.1);
    });

    $("#zoomOut").click(function() {
        $image.cropper("zoom", -0.1);
    });

    $("#rotateLeft").click(function() {
        $image.cropper("rotate", 45);
    });

    $("#rotateRight").click(function() {
        $image.cropper("rotate", -45);
    });
  });
</script>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.picture %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @admin.picture %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iGrid监控平台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon_logo.ico" %>
</head>

	<body>
		<div id="wrapper">
			<!-- 左侧导航栏部分 -->
			<%= render partial: "/share/left_bar" %>

			<!-- 右侧内容页 -->
			<div id="page-wrapper" class="gray-bg">
				<!-- 顶部导航 -->
				<%= render partial: "/share/top_bar" %>

				<!-- 右侧中间内容部分 -->
				<div class="row wrapper eagle-content <%= controller.controller_path.gsub('/','__') + '__' + controller.action_name %>">
					<%= yield %>
				</div>

				<!-- 页脚 -->
				<%= render partial: "/share/footer" %>

				<!-- 皮肤及设置 -->
				<%= render partial: "/share/setting" %>
			</div>
		</div>	
	</body>

</html>

app/views/security/air_condition.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "air_condition.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/chart.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-6">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Bar Chart Example </h5>
        </div>
        <div class="ibox-content">
          <div id="morris-bar-chart">
          	<div style="height:280px" id="pue"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Bar Chart Example </h5>
        </div>
        <div class="ibox-content">
          <div id="morris-bar-chart">
          	<div style="height:280px" id="pie"></div>
          </div>
        </div>
      </div>
    </div>
	</div>
	<div class="row">
		<div class="col-lg-6">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Bar Chart Example </h5>
        </div>
        <div class="ibox-content">
          <div id="morris-bar-chart">
          	<div style="height:280px" id="bar"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Bar Chart Example </h5>
        </div>
        <div class="ibox-content">
          <div id="morris-bar-chart">
          	<div style="height:280px" id="bars"></div>
          </div>
        </div>
      </div>
    </div>
	</div>
</div>

<script type="text/javascript">
	// 路径配置
	require.config({
		paths: {
			echarts: '/assets/echarts'
		}
	});	
	// pue图表
	require(
	[
		'echarts',
		'echarts/chart/gauge'
	],
	function (pue){
		var pueChart = pue.init(document.getElementById('pue')); 
		var option = {
			tooltip : {
				formatter: "{a} <br/>{b} : {c}%"
			},
			series : [
				{
					name:'业务指标',
					type:'gauge',
					center: ['50%', '50%'],
					radius: [0, '100%'],
					detail : {formatter:'{value}%'},
					data:[{value: 64}]
				}
			]
		};
			pueChart.setOption(option, true);
	}
);
</script>


<script type="text/javascript">
	// 路径配置
	require.config({
		paths: {
			echarts: '/assets/echarts'
		}
	});	
	// 饼图表
	require(
	[
		'echarts',
		'echarts/chart/pie'
	],
	function (pie){
		var pieChart = pie.init(document.getElementById('pie')); 
		var option = {
		    tooltip : {
		        trigger: 'item',
		        formatter: "{a} <br/>{b} : {c} ({d}%)"
		    },
		    legend: {
		        orient : 'vertical',
		        x : 'left',
		        data:['物业人员的工资和福利','建筑物的维修和保养','设备维护和保养','保洁费用','绿化费用','治安和防盗费用','公共水电费','日常办公费用']
		    },
		    calculable : true,
		    series : [
		        {
		            name:'访问来源',
		            type:'pie',
		            radius : '55%',
		            center: ['60%', '50%'],
		            data:[
		                {value:400, name:'物业人员的工资和福利'},
		                {value:150, name:'建筑物的维修和保养'},
		                {value:100, name:'设备维护和保养'},
		                {value:50, name:'保洁费用'},
		                {value:50, name:'绿化费用'},
		                {value:80, name:'治安和防盗费用'},
		                {value:70, name:'公共水电费'},
		                {value:100, name:'日常办公费用'}
		            ]
		        }
		    ]
		};
		pieChart.setOption(option); 
	}
);
</script>

<script type="text/javascript">
	// 路径配置
	require.config({
		paths: {
			echarts: '/assets/echarts'
		}
	});	
	// bar图表
	require(
	[
		'echarts',
		'echarts/chart/bar'
	],
	function (bar){
		var barChart = bar.init(document.getElementById('bar')); 
		var option = {
		    tooltip : {
		        trigger: 'axis'
		    },
		    legend: {
		        data:['预算','实际支出']
		    },
		    calculable : true,
		    xAxis : [
		        {
		            type : 'category',
		            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
		        }
		    ],
		    yAxis : [
		        {
		            type : 'value'
		        }
		    ],
		    series : [
		        {
		            name:'预算',
		            type:'bar',
		            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
		        },
		        {
		            name:'实际支出',
		            type:'bar',
		            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
		        }
		    ]
		};
		barChart.setOption(option); 
	}
);
</script>

<script type="text/javascript">
	// 路径配置
	require.config({
		paths: {
			echarts: '/assets/echarts'
		}
	});	
	// bar图表
	require(
	[
		'echarts',
		'echarts/chart/bar'
	],
	function (bars){
		var barsChart = bars.init(document.getElementById('bars')); 
		var option = {
		    tooltip : {
		        trigger: 'axis'
		    },
		    legend: {
		        data:['本月','上月']
		    },
		    calculable : true,
		    xAxis : [
		        {
		            type : 'category',
		            data : ['物业','建筑','设备','保洁','绿化','治安','水电','办公']
		        }
		    ],
		    yAxis : [
		        {
		            type : 'value'
		        }
		    ],
		    series : [
		        {
		            name:'本月',
		            type:'bar',
		            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2],
		        },
		        {
		            name:'上月',
		            type:'bar',
		            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2],
		        }
		    ]
		};
		barsChart.setOption(option); 
	}
);
</script>

app/views/security/dewatering.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "dewatering.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/door.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "door.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/entrance_guard.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture text-center">
    <%= image_tag "entrance_guard.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/evevator.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "evevator.png", class: "img-responsive",width:"100%" %>
    </div>
    <div class="col-md-4 text-center">
      <table class="eve-table left-table table table-striped">
        <tr>
          <td>启动状态：</td>
          <td>使用</td>
        </tr>
        <tr>
          <td>运行状态：</td>
          <td>停止</td>
        </tr>
        <tr>
          <td>故障报警：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>上下行：</td>
          <td></td>
        </tr>
        <tr>
          <td>滤水检测：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>轿厢温度：</td>
          <td>24℃</td>
        </tr>
        <tr>
          <td>负责范围：</td>
          <td>步行街-1F——3F</td>
        </tr>
      </table>
    </div>
    <div class="col-md-4 text-center">
      <table class="eve-table center-table table table-striped">
        <tr>
          <td>启动状态：</td>
          <td>使用</td>
        </tr>
        <tr>
          <td>运行状态：</td>
          <td>停止</td>
        </tr>
        <tr>
          <td>故障报警：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>上下行：</td>
          <td></td>
        </tr>
        <tr>
          <td>滤水检测：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>轿厢温度：</td>
          <td>24℃</td>
        </tr>
        <tr>
          <td>负责范围：</td>
          <td>步行街-1F——3F</td>
        </tr>
      </table>
    </div>
    <div class="col-md-4 text-center">
      <table class="eve-table right-table table table-striped">
        <tr>
          <td>启动状态：</td>
          <td>使用</td>
        </tr>
        <tr>
          <td>运行状态：</td>
          <td>停止</td>
        </tr>
        <tr>
          <td>故障报警：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>上下行：</td>
          <td></td>
        </tr>
        <tr>
          <td>滤水检测：</td>
          <td>正常</td>
        </tr>
        <tr>
          <td>轿厢温度：</td>
          <td>24℃</td>
        </tr>
        <tr>
          <td>负责范围：</td>
          <td>步行街-1F——3F</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/security/index.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="text-danger">
    <%#= image_tag "home.png", class: "img-responsive" %>
    您还没有可监控的区域！
  </div>
</div>

app/views/security/infrared.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "infrared.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/lighting.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture col-md-12">
    <%#= image_tag "infrared.png", class: "img-responsive", width:"100%" %>
    <% 6.times do |i| %>
    <div class="col-md-4 lighting-off">
    <div class="col-md-12 light-tab">
      <div class="col-md-5">
        <%= image_tag "lighting_on.png", class: "img-responsive", width:"100%" %>
      </div>
      <div class="col-md-7">
        <div class="col-md-12"><p>运行时间</p><p>08：30：30</p></div>
        <div class="col-md-12 btn-table">
          <table>
            <tr>
              <td style="background-color: #7f7f7f; color: #fff">开启</td>
              <td>手动</td>
              <td>自动</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/security/park.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "park.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/security/phone.html.erb
<div class="text-center animated fadeInRightBig clearfix">
  <div class="left-nav">
    <div class="show-picture">
    <%= image_tag "phone.png", class: "img-responsive", width:"100%" %>
    </div>
  </div>
</div>

app/views/share/_footer.html.erb
<div class="footer">
	<div class="pull-right">
		<%= Time.now.strftime("%F") %>
	</div>
	<div>
		<strong>Copyright</strong> Example Company &copy; 2014-2015
	</div>
</div>

app/views/share/_left_bar.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<!-- brand -->
				<li id="leftbar_first_li"></li>
				<li class="<%= "active" if params[:controller] == 'security'&& params[:action] == 'evevator' %>">
					<%= link_to evevator_security_index_path do %>
						<i class="fa fa-building"></i> <span class="nav-label">电梯界面</span></span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'infrared' %>" >
					<%= link_to infrared_security_index_path do %>
					<i class="fa fa-sliders"></i> <span class="nav-label">红外入侵告警界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'air_condition' %>" >
					<%= link_to air_condition_security_index_path do %>
					<i class="fa fa-leaf"></i> <span class="nav-label">空调界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'door' %>" >
					<%= link_to door_security_index_path do %>
					<i class="fa fa-columns"></i> <span class="nav-label">门界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'entrance_guard' %>" >
					<%= link_to entrance_guard_security_index_path do %>
					<i class="fa fa-shield"></i> <span class="nav-label">门禁界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'dewatering' %>" >
					<%= link_to dewatering_security_index_path do %>
					<i class="fa fa-road"></i> <span class="nav-label">排水系统界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'park' %>" >
					<%= link_to park_security_index_path do %>
					<i class="fa fa-car"></i> <span class="nav-label">停车场界面</span>
					<% end %>
				</li>

				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'lighting' %>" >
					<%= link_to lighting_security_index_path do %>
					<i class="fa fa-fire"></i> <span class="nav-label">照明系统界面</span>
					<% end %>
				</li>
				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'chart' %>" >
					<%= link_to chart_security_index_path do %>
					<i class="fa fa-money"></i> <span class="nav-label">费用监控界面</span>
					<% end %>
				</li>
				<li class="<%= 'active' if params[:controller] == 'security' && params[:action] == 'phone' %>" >
					<%= link_to phone_security_index_path do %>
					<i class="fa fa-tablet"></i> <span class="nav-label">手机APP界面</span>
					<% end %>
				</li>
		</ul>
	</div>
</nav>

app/views/share/_top_bar.html.erb
<div class="row border-bottom">
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; background: #1F3446;">
		<!-- 左侧导航栏收起按钮 -->
		<div class="navbar-header">
			<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
			<a href="<%= root_path %>" class="navbar-brand"><strong>iGrid Total Solution</strong></a>
		</div>
		<!-- 左侧导航栏收起按钮  end-->
		<!-- 右上角消息提示部分 -->
		<ul class="nav navbar-top-links navbar-right">
			<li><span class="m-r-sm text-muted glyphicon glyphicon-stats"></span></li>
			<li><strong class="m-r-sm text-muted welcome-message"><%= Time.now.strftime("%A %R %p")%></strong></li>
			<li><%= image_tag "favicon_logo.ico" %></li>
		</ul>
		<!-- 右上角消息提示部分 end-->
	</nav>
</div>

app/views/welcome/index.html.erb
<div class="text-center animated fadeInRightBig clearfix">
	<div class="text-danger">
		<%#= image_tag "home.png", class: "img-responsive" %>
    
	</div>
</div>